DROP DATABASE IF EXISTS user_ejsDB;
CREATE DATABASE user_ejsDB;
USE user_ejsDB;

CREATE TABLE Users (
    id INTEGER(11) AUTO_INCREMENT NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);